### PR TITLE
Laravel 6.* support

### PR DESCRIPTION
**Pull request by trideout**
Fix for depricated snake_case string helper and updated composer.json to allow for laravel 6.

### CODE REVIEW

**Comment by mbardelmeijer** [comment]
@schuppo any chance to merge this? Would love to see support for Laravel 6+ as well.

**Comment by yizen** [comment]
@schuppo I concur: this is currently blocking our Laravel 6 migration, could you have a look at this PR ?

**Comment by danhunsaker** [comment]
Also a blocker on [LaraComic](https://github.com/danhunsaker/laracomic)'s Laravel 6.x upgrade. Would love to see this merged!

**Comment by schuppo** [comment]
Sorry for the long waiting and thanks for contributing

**Comment by mbardelmeijer** [comment]
@schuppo thx for merging! Could you perhaps tag a new release as well?

**Pull request merged**
